# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS - PostgreSQL
# ==========================================
spring.datasource.url=jdbc:postgresql://pg-back-planetas-back-planetas.d.aivencloud.com:26997/defaultdb?
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_62G3Dgm7N4EwHQwcwRs
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURACIÓN JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# INICIALIZACIÓN SQL
# ==========================================


# ==========================================
# CONFIGURACIÓN DEL SERVIDOR
# ==========================================
server.port=8080

# ==========================================
# CONFIGURACIÓN SPRINGDOC / SWAGGER
# ==========================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# ==========================================
# LOGGING
# ==========================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
